name: Solution-Task-2-Push
on:
  push:
    branches: ["main"]
jobs:
  build-test:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test 
      run: dotnet test